import "../styles/globals.css";
import "../styles/variables.css";
import "katex/dist/katex.min.css";
import type { Metadata } from "next";
import { HeaderNav } from "./components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Matthew Goldfield</title>
      </head>
      <body className="dark:bg-slate-800">
        <header className="">
          <HeaderNav />
        </header>
        <div>
          {children}
        </div>
      </body>
    </html>
  );
}
