import "../styles/globals.css";
import "../styles/variables.css";
import type { Metadata } from "next";
import { HeaderNav, Title } from "./helpers";
import styles from "./page.module.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Matthew Goldfield</title>
      </head>
      <body>
        <header className={styles.header}>
          <Title />
          <HeaderNav />
        </header>
        {children}
      </body>
    </html>
  );
}
